//
// Created by Troldal on 05/07/2023.
//

#ifndef XLTHERMO_DATA_COMPCORRELATIONS_HPP
#define XLTHERMO_DATA_COMPCORRELATIONS_HPP

class CompCorrelations
{
};

#endif    // XLTHERMO_DATA_COMPCORRELATIONS_HPP
